import { UserEntity } from './user.entity';
import { BusinessServiceEntity } from './business-service.entity';
import { BusinessHoursEntity } from './business-hours.entity';
import { BusinessImageEntity } from './business-image.entity';
import { BusinessBankingDetailsEntity } from './business-banking-details.entity';
export declare class BusinessEntity {
    id: string;
    name: string;
    abn: string;
    owner_name: string;
    business_email: string;
    business_mobile: string;
    business_address: string;
    suburb: string;
    postcode: string;
    state: string;
    service_radius: number;
    website_url?: string;
    description?: string;
    experience?: string;
    qualifications?: string;
    licences?: string;
    avg_rating: number;
    total_reviews: number;
    is_verified: boolean;
    is_approved: boolean;
    approval_status: string;
    rejection_reason?: string;
    is_suspended: boolean;
    suspension_reason?: string;
    latitude?: number;
    longitude?: number;
    created_at: Date;
    updated_at: Date;
    user: UserEntity;
    services: BusinessServiceEntity[];
    business_hours: BusinessHoursEntity[];
    images: BusinessImageEntity[];
    banking_details: BusinessBankingDetailsEntity[];
    get service_radius_km(): number;
    set service_radius_km(v: number);
    get website(): string | undefined;
    set website(v: string | undefined);
    get hours(): BusinessHoursEntity[];
    set hours(v: BusinessHoursEntity[]);
    get average_rating(): number;
    set average_rating(v: number);
}
